### PR TITLE
Upgrade to twitter-cldr-js v3.0.0. Bump version to 2.0.0.

### PR DESCRIPTION
**Pull request by radzinzki**
No changes to the contributing guidelines (unlike #7). Only the bundles have been updated, and  `core.js` and `core.min.js` added

@KL-7 @camertron

### CODE REVIEW

**Comment by camertron** [comment]
Looks good to me. I assume this is because of the data/logic separation in twitter-cldr-js?

**Comment by radzinzki** [comment]
Yep, that's correct.

**Comment by radzinzki** [comment]
@camertron i'll update this branch with the latest RBNF fixes, then we can merge this as well

**Comment by camertron** [comment]
Cool sounds good :)

**Comment by radzinzki** [comment]
done!

**Pull request merged**
