### PR TITLE
Update build after data / logic separation

### PR DESCRIPTION
**Pull request by radzinzki**
Also:
- reorganize the project for future builds.
- update CONTRIBUTING.md to reflect these changes.

@camertron @KL-7

### CODE REVIEW

**Comment by radzinzki** [comment]
This should be merged after https://github.com/twitter/twitter-cldr-js/pull/62 is merged

**Comment by KL-7** [comment]
:shipit:

**Comment by radzinzki** [comment]
OK, I need to change this now to use the new filenames. I'll do that once the other PR is merged

**Comment by radzinzki** [comment]
Closing in favour of #8

**Comment by radzinzki** [comment]
Closing in favour of #8 (Minor git snafu on my part, oops!)

**Pull request closed without merging**
